on:
  push:
    branches:
      - main
name: Deploy website
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: get node
      uses: actions/setup-node@v2
      with:
        node-version: '24'
    - name: build
      run: |
        npm install
        npm run build      

    - name: rsync
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        path: _site/
        remote_path: /var/www/html/
        remote_host: 159.89.218.57
        remote_user: root
        remote_key: ${{ secrets.THATSVNCLUBSSHPRIVATEKEY }}
